remote_theme: pointbar/minima
title: Recettes des ateliers cuisine des Gourmandignes
author: Association Gourmandignes
email: contact@bgourmandignes.org
description : des recettes simples réalisées avec des produits issus des producteurs locaux
github_username: akakeronos
twitter_username: gourmandignes
